# Sample Jupyter Notebook to study filtering from dataframes

Data source: Comprehensive Car Market Analysis
https://www.kaggle.com/datasets/lalit7881/comprehensive-car-market-analysis/data
Copyright status: CC0 Public Domain

In [4]:
import pandas as pd

df_carsales = pd.read_csv('data/v1-legacy-carapi-datafeed-sample.csv')

In [6]:
# data sanity check
df_carsales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17707 entries, 0 to 17706
Data columns (total 57 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Make Id                                      17707 non-null  int64
 1   Make Name                                    17707 non-null  object
 2   Model Id                                     17707 non-null  int64
 3   Model Name                                   17707 non-null  object
 4   Trim Id                                      17707 non-null  int64
 5   Trim Year                                    17707 non-null  int64
 6   Trim Name                                    17707 non-null  object
 7   Trim Description                             17707 non-null  object
 8   Trim Msrp                                    17707 non-null  int64
 9   Trim Invoice                                 17704 non-null  float64
 10  Trim Created                                 17707 non-null  object
 11  Trim Modified                                17707 non-null  object
 12  Engine Id                                    17673 non-null  float64
 13  Engine Type                                  17673 non-null  object
 14  Engine Fuel Type                             17673 non-null  object
 15  Engine Cylinders                             17452 non-null  object
 16  Engine Size                                  17452 non-null  float64
 17  Engine Horsepower Hp                         17531 non-null  float64
 18  Engine Horsepower Rpm                        17147 non-null  float64
 19  Engine Torque Ft Lbs                         17192 non-null  float64
 20  Engine Torque Rpm                            16873 non-null  float64
 21  Engine Valves                                17449 non-null  float64
 22  Engine Valve Timing                          16346 non-null  object
 23  Engine Cam Type                              17449 non-null  object
 24  Engine Drive Type                            17673 non-null  object
 25  Engine Transmission                          17673 non-null  object
 26  Body Id                                      17707 non-null  int64
 27  Body Type                                    17707 non-null  object
 28  Body Doors                                   17707 non-null  int64
 29  Body Seats                                   17673 non-null  float64
 30  Body Length                                  17562 non-null  float64
 31  Body Width                                   16794 non-null  float64
 32  Body Height                                  17408 non-null  float64
 33  Body Wheel Base                              17574 non-null  float64
 34  Body Front Track                             341 non-null    float64
 35  Body Rear Track                              341 non-null    float64
 36  Body Ground Clearance                        11570 non-null  float64
 37  Body Cargo Capacity                          12677 non-null  float64
 38  Body Max Cargo Capacity                      8801 non-null   float64
 39  Body Curb Weight                             15726 non-null  float64
 40  Body Gross Weight                            10835 non-null  float64
 41  Body Max Payload                             9151 non-null   float64
 42  Body Max Towing Capacity                     9654 non-null   float64
 43  Mileage Id                                   17673 non-null  float64
 44  Mileage Fuel Tank Capacity                   17136 non-null  float64
 45  Mileage Combined Mpg                         14633 non-null  float64
 46  Mileage Epa City Mpg                         14565 non-null  float64
 47  Mileage Epa Highway Mpg                      14565 non-null  float64
 48  Mileage Range City                           17449 non-null  float64
 49  Mileage Range Highway                        17449 non-null  float64
 50  Mileage Epa Combined Mpg Electric            462 non-null    float64
 51  Mileage Epa City Mpg Electric                389 non-null    float64
 52  Mileage Epa Highway Mpg Electric             389 non-null    float64
 53  Mileage Range Electric                       325 non-null    float64
 54  Mileage Epa Kwh 100 Mi Electric              299 non-null    float64
 55  Mileage Epa Time To Charge Hr 240v Electric  316 non-null    float64
 56  Mileage Battery Capacity Electric            161 non-null    float64
dtypes: float64(36), int64(7), object(14)
memory usage: 7.7+ MB

In [7]:
df_carsales.head()

,Make Id,Make Name,Model Id,Model Name,Trim Id,Trim Year,Trim Name,Trim Description,Trim Msrp,Trim Invoice,...,Mileage Epa Highway Mpg,Mileage Range City,Mileage Range Highway,Mileage Epa Combined Mpg Electric,Mileage Epa City Mpg Electric,Mileage Epa Highway Mpg Electric,Mileage Range Electric,Mileage Epa Kwh 100 Mi Electric,Mileage Epa Time To Charge Hr 240v Electric,Mileage Battery Capacity Electric
0,1,Acura,97,ILX,6292,2020,Base,4dr Sedan (2.4L 4cyl 8AM),25900,24617.0,...,34.0,317.0,449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Acura,97,ILX,6295,2020,Premium and A-SPEC Packages,Premium and A-SPEC Packages 4dr Sedan (2.4L 4c...,29750,28264.0,...,34.0,317.0,449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Acura,97,ILX,6293,2020,Premium Package,Premium Package 4dr Sedan (2.4L 4cyl 8AM),27750,26370.0,...,34.0,317.0,449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Acura,97,ILX,6296,2020,Technology and A-SPEC Packages,Technology and A-SPEC Packages 4dr Sedan (2.4L...,31650,30064.0,...,34.0,317.0,449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Acura,97,ILX,6294,2020,Technology Package,Technology Package 4dr Sedan (2.4L 4cyl 8AM),29650,28169.0,...,34.0,317.0,449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df_carsales.index

RangeIndex(start=0, stop=17707, step=1)

In [11]:
#basic selection
#output: dataframe
df_carsales[["Make Name","Model Id"]]

      Make Name  Model Id
0         Acura        97
1         Acura        97
2         Acura        97
3         Acura        97
4         Acura        97
...         ...       ...
17702     Volvo       589
17703     Volvo       589
17704     Volvo       589
17705     Volvo       589
17706     Volvo       589

[17707 rows x 2 columns]

In [12]:
type(df_carsales[["Make Name","Model Id"]])

pandas.core.frame.DataFrame

In [13]:
#position based selection
# scalar value
df_carsales.iloc[2,2]

np.int64(97)

In [20]:
#all rows from the second column
df_carsales.iloc[:, 1]

0        Acura
1        Acura
2        Acura
3        Acura
4        Acura
         ...
17702    Volvo
17703    Volvo
17704    Volvo
17705    Volvo
17706    Volvo
Name: Make Name, Length: 17707, dtype: object

In [21]:
#all columns
df_carsales.iloc[0:]

,Make Id,Make Name,Model Id,Model Name,Trim Id,Trim Year,Trim Name,Trim Description,Trim Msrp,Trim Invoice,...,Mileage Epa Highway Mpg,Mileage Range City,Mileage Range Highway,Mileage Epa Combined Mpg Electric,Mileage Epa City Mpg Electric,Mileage Epa Highway Mpg Electric,Mileage Range Electric,Mileage Epa Kwh 100 Mi Electric,Mileage Epa Time To Charge Hr 240v Electric,Mileage Battery Capacity Electric
0,1,Acura,97,ILX,6292,2020,Base,4dr Sedan (2.4L 4cyl 8AM),25900,24617.0,...,34.0,317.0,449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Acura,97,ILX,6295,2020,Premium and A-SPEC Packages,Premium and A-SPEC Packages 4dr Sedan (2.4L 4c...,29750,28264.0,...,34.0,317.0,449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Acura,97,ILX,6293,2020,Premium Package,Premium Package 4dr Sedan (2.4L 4cyl 8AM),27750,26370.0,...,34.0,317.0,449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Acura,97,ILX,6296,2020,Technology and A-SPEC Packages,Technology and A-SPEC Packages 4dr Sedan (2.4L...,31650,30064.0,...,34.0,317.0,449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Acura,97,ILX,6294,2020,Technology Package,Technology Package 4dr Sedan (2.4L 4cyl 8AM),29650,28169.0,...,34.0,317.0,449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17702,23,Volvo,589,XC70,23951,2015,3.2,3.2 4dr Wagon AWD (3.2L 6cyl 6A),36900,34686.0,...,25.0,333.0,463.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17703,23,Volvo,589,XC70,23950,2015,T5 Drive-E,T5 Drive-E 4dr Wagon (2.0L 4cyl Turbo 8A),36050,33887.0,...,31.0,444.0,574.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17704,23,Volvo,589,XC70,23949,2015,T5 Drive-E,T5 Drive-E 4dr Wagon (2.0L 4cyl Turbo 8A),35400,33276.0,...,31.0,444.0,574.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17705,23,Volvo,589,XC70,23954,2015,T6,T6 4dr Wagon AWD (3.0L 6cyl Turbo 6A),42050,39527.0,...,24.0,315.0,444.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17706,23,Volvo,589,XC70,23953,2015,T6,T6 4dr Wagon AWD (3.0L 6cyl Turbo 6A),41800,39292.0,...,24.0,315.0,444.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
#finding special elements
#first and second rows, last and last but one columns as dataframes
df_carsales.iloc[[0,1],[-1,-2]]

,Mileage Battery Capacity Electric,Mileage Epa Time To Charge Hr 240v Electric
0,NaN,NaN
1,NaN,NaN